services:

  postgres:
    image: postgres:16.1
    container_name: postgres
    environment:
     POSTGRES_DB: documentdb
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
    - document-network

  web:
    build: web
    container_name: web
    ports:
      - "1080:8080"
    networks:
      - document-network
    environment:
      spring__datasource__url: jdbc:postgresql://postgres:5432/documentdb
      spring__datasource__username: postgres
      spring__datasource__password: postgres

networks:
  document-network:
    driver: bridge

volumes:
  postgres_data:
